In [2]:
import json
import pandas as pd

with open("kent_care_homes.json", "r", encoding="utf-8") as file:
    kent_care_homes = json.load(file)

with open("medway_care_homes.json", "r", encoding="utf-8") as file:
    medway_care_homes = json.load(file)

print("Kent records:", len(kent_care_homes))
print("Medway records:", len(medway_care_homes))

Kent records: 1123
Medway records: 151

In [3]:
kent_df = pd.json_normalize(kent_care_homes)
medway_df = pd.json_normalize(medway_care_homes)

print("Kent shape:", kent_df.shape)
print("Medway shape:", medway_df.shape)

Kent shape: (1123, 55)
Medway shape: (151, 54)

In [4]:
print(kent_df.columns.tolist())

['locationId', 'providerId', 'organisationType', 'type', 'name', 'onspdCcgCode', 'onspdCcgName', 'onspdIcbCode', 'onspdIcbName', 'registrationStatus', 'registrationDate', 'deregistrationDate', 'dormancy', 'onspdLatitude', 'onspdLongitude', 'careHome', 'inspectionDirectorate', 'postalAddressLine1', 'postalAddressTownCity', 'postalAddressCounty', 'region', 'postalCode', 'mainPhoneNumber', 'numberOfBeds', 'constituency', 'localAuthority', 'relationships', 'locationTypes', 'regulatedActivities', 'gacServiceTypes', 'specialisms', 'inspectionCategories', 'inspectionAreas', 'reports', 'lastInspection.date', 'currentRatings.overall.rating', 'currentRatings.overall.keyQuestionRatings', 'odsCode', 'postalAddressLine2', 'uprn', 'website', 'historicRatings', 'assessmentServiceGroup', 'assessment', 'lastReport.publicationDate', 'dormancyEndDate', 'currentRatings.overall.reportDate', 'currentRatings.overall.reportLinkId', 'currentRatings.reportDate', 'brandId', 'brandName', 'registeredManagerAbsentDate', 'dormancyStartDate', 'currentRatings.serviceRatings', 'alsoKnownAs']

In [5]:
kent_df.head(3)

,locationId,providerId,organisationType,type,name,onspdCcgCode,onspdCcgName,onspdIcbCode,onspdIcbName,registrationStatus,...,dormancyEndDate,currentRatings.overall.reportDate,currentRatings.overall.reportLinkId,currentRatings.reportDate,brandId,brandName,registeredManagerAbsentDate,dormancyStartDate,currentRatings.serviceRatings,alsoKnownAs
0,1-1002113960,1-942188853,Location,Social Care Org,Elmwood,E38000237,NHS Kent and Medway CCG,E54000032,NHS Kent and Medway Integrated Care Board,Deregistered,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1-1010200899,1-935571070,Location,Social Care Org,The Hall,E38000237,NHS Kent and Medway CCG,E54000032,NHS Kent and Medway Integrated Care Board,Deregistered,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1-1010200978,1-935571070,Location,Social Care Org,Ashlea House,E38000237,NHS Kent and Medway CCG,E54000032,NHS Kent and Medway Integrated Care Board,Registered,...,2025-10-23,2019-07-12,3fc8b61f-5219-404d-9af2-f5ef865d9949,2019-07-12,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
kent_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1123 entries, 0 to 1122
Data columns (total 55 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   locationId                                 1123 non-null   object
 1   providerId                                 1123 non-null   object
 2   organisationType                           1123 non-null   object
 3   type                                       1123 non-null   object
 4   name                                       1123 non-null   object
 5   onspdCcgCode                               1118 non-null   object
 6   onspdCcgName                               1118 non-null   object
 7   onspdIcbCode                               1115 non-null   object
 8   onspdIcbName                               1115 non-null   object
 9   registrationStatus                         1123 non-null   object
 10  registrationDate                           1123 non-null   object
 11  deregistrationDate                         621 non-null    object
 12  dormancy                                   1123 non-null   object
 13  onspdLatitude                              1122 non-null   float64
 14  onspdLongitude                             1122 non-null   float64
 15  careHome                                   1123 non-null   object
 16  inspectionDirectorate                      1123 non-null   object
 17  postalAddressLine1                         1123 non-null   object
 18  postalAddressTownCity                      1123 non-null   object
 19  postalAddressCounty                        1002 non-null   object
 20  region                                     1123 non-null   object
 21  postalCode                                 1123 non-null   object
 22  mainPhoneNumber                            1071 non-null   object
 23  numberOfBeds                               1123 non-null   int64
 24  constituency                               1123 non-null   object
 25  localAuthority                             1123 non-null   object
 26  relationships                              1123 non-null   object
 27  locationTypes                              1123 non-null   object
 28  regulatedActivities                        1123 non-null   object
 29  gacServiceTypes                            1123 non-null   object
 30  specialisms                                1123 non-null   object
 31  inspectionCategories                       974 non-null    object
 32  inspectionAreas                            1123 non-null   object
 33  reports                                    951 non-null    object
 34  lastInspection.date                        947 non-null    object
 35  currentRatings.overall.rating              846 non-null    object
 36  currentRatings.overall.keyQuestionRatings  846 non-null    object
 37  odsCode                                    794 non-null    object
 38  postalAddressLine2                         495 non-null    object
 39  uprn                                       792 non-null    object
 40  website                                    677 non-null    object
 41  historicRatings                            678 non-null    object
 42  assessmentServiceGroup                     157 non-null    object
 43  assessment                                 157 non-null    object
 44  lastReport.publicationDate                 786 non-null    object
 45  dormancyEndDate                            53 non-null     object
 46  currentRatings.overall.reportDate          650 non-null    object
 47  currentRatings.overall.reportLinkId        650 non-null    object
 48  currentRatings.reportDate                  650 non-null    object
 49  brandId                                    490 non-null    object
 50  brandName                                  490 non-null    object
 51  registeredManagerAbsentDate                58 non-null     object
 52  dormancyStartDate                          28 non-null     object
 53  currentRatings.serviceRatings              3 non-null      object
 54  alsoKnownAs                                3 non-null      object
dtypes: float64(2), int64(1), object(52)
memory usage: 482.7+ KB

In [7]:
missing = kent_df.isna().sum()

print(missing[missing > 0].sort_values(ascending=False))

alsoKnownAs                                  1120
currentRatings.serviceRatings                1120
dormancyStartDate                            1095
dormancyEndDate                              1070
registeredManagerAbsentDate                  1065
assessmentServiceGroup                        966
assessment                                    966
brandName                                     633
brandId                                       633
postalAddressLine2                            628
deregistrationDate                            502
currentRatings.reportDate                     473
currentRatings.overall.reportDate             473
currentRatings.overall.reportLinkId           473
website                                       446
historicRatings                               445
lastReport.publicationDate                    337
uprn                                          331
odsCode                                       329
currentRatings.overall.keyQuestionRatings     277
currentRatings.overall.rating                 277
lastInspection.date                           176
reports                                       172
inspectionCategories                          149
postalAddressCounty                           121
mainPhoneNumber                                52
onspdIcbName                                    8
onspdIcbCode                                    8
onspdCcgName                                    5
onspdCcgCode                                    5
onspdLongitude                                  1
onspdLatitude                                   1
dtype: int64

In [8]:
for i, col in enumerate(kent_df.columns, start=1):
    print(f"{i}. {col}")

1. locationId
2. providerId
3. organisationType
4. type
5. name
6. onspdCcgCode
7. onspdCcgName
8. onspdIcbCode
9. onspdIcbName
10. registrationStatus
11. registrationDate
12. deregistrationDate
13. dormancy
14. onspdLatitude
15. onspdLongitude
16. careHome
17. inspectionDirectorate
18. postalAddressLine1
19. postalAddressTownCity
20. postalAddressCounty
21. region
22. postalCode
23. mainPhoneNumber
24. numberOfBeds
25. constituency
26. localAuthority
27. relationships
28. locationTypes
29. regulatedActivities
30. gacServiceTypes
31. specialisms
32. inspectionCategories
33. inspectionAreas
34. reports
35. lastInspection.date
36. currentRatings.overall.rating
37. currentRatings.overall.keyQuestionRatings
38. odsCode
39. postalAddressLine2
40. uprn
41. website
42. historicRatings
43. assessmentServiceGroup
44. assessment
45. lastReport.publicationDate
46. dormancyEndDate
47. currentRatings.overall.reportDate
48. currentRatings.overall.reportLinkId
49. currentRatings.reportDate
50. brandId
51. brandName
52. registeredManagerAbsentDate
53. dormancyStartDate
54. currentRatings.serviceRatings
55. alsoKnownAs

In [9]:
print("Registration status:")
print(kent_df["registrationStatus"].value_counts(dropna=False))

print("\nCare home:")
print(kent_df["careHome"].value_counts(dropna=False))

print("\nOrganisation type:")
print(kent_df["organisationType"].value_counts(dropna=False))

print("\nDuplicate location IDs:")
print(kent_df["locationId"].duplicated().sum())

print("\nDuplicate provider IDs:")
print(kent_df["providerId"].duplicated().sum())

Registration status:
registrationStatus
Deregistered    621
Registered      502
Name: count, dtype: int64

Care home:
careHome
Y    1123
Name: count, dtype: int64

Organisation type:
organisationType
Location    1123
Name: count, dtype: int64

Duplicate location IDs:
0

Duplicate provider IDs:
487

In [10]:
kent_df.groupby("registrationStatus")[[
    "locationId",
    "providerId",
    "name",
    "postalCode",
    "registrationDate",
    "deregistrationDate"
]].head(3)

,locationId,providerId,name,postalCode,registrationDate,deregistrationDate
0,1-1002113960,1-942188853,Elmwood,ME15 7DR,2013-11-26,2014-12-19
1,1-1010200899,1-935571070,The Hall,TN26 2EW,2013-10-25,2024-09-05
2,1-1010200978,1-935571070,Ashlea House,TN24 9BP,2013-10-25,NaN
3,1-1010201117,1-935571070,Birch House,TN26 2AF,2013-10-25,NaN
4,1-10205172753,1-9928054001,Hothfield Neurological Rehabilitation Centre,TN26 1AZ,2021-03-05,NaN
6,1-1033394718,1-116864941,The Peter Gidney Neurodisability Centre,DA2 7QT,2013-11-07,2016-11-25

In [11]:
kent_clean = kent_df[
    kent_df["registrationStatus"].str.strip().str.lower() == "registered"
].copy()

print("Original Kent records:", len(kent_df))
print("Registered Kent records:", len(kent_clean))

Original Kent records: 1123
Registered Kent records: 502

In [12]:
kent_clean["registrationStatus"].value_counts()

registrationStatus
Registered    502
Name: count, dtype: int64

In [13]:
text_columns = [
    "name",
    "registrationStatus",
    "organisationType",
    "postalAddressTownCity",
    "postalAddressCounty",
    "region",
    "postalCode",
    "localAuthority"
]

for col in text_columns:
    if col in kent_clean.columns:
        kent_clean[col] = kent_clean[col].astype("string").str.strip()

In [14]:
print(kent_clean["postalCode"].head(10))

2     TN24 9BP
3     TN26 2AF
4     TN26 1AZ
5      CT7 9EZ
7      ME9 8NE
10    CT16 2PU
13     DA1 2GA
14    CT10 1QL
18    CT19 4PX
19    CT19 4PX
Name: postalCode, dtype: string

In [15]:
print("Missing postcodes:", kent_clean["postalCode"].isna().sum())

Missing postcodes: 0

In [16]:
kent_clean["postalCode"] = (
    kent_clean["postalCode"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

print(kent_clean["postalCode"].head(10))

2     TN24 9BP
3     TN26 2AF
4     TN26 1AZ
5      CT7 9EZ
7      ME9 8NE
10    CT16 2PU
13     DA1 2GA
14    CT10 1QL
18    CT19 4PX
19    CT19 4PX
Name: postalCode, dtype: string

In [17]:
print("Duplicate postcodes:", kent_clean["postalCode"].duplicated().sum())

Duplicate postcodes: 59

In [18]:
print(kent_clean["localAuthority"].value_counts(dropna=False))

localAuthority
Kent    502
Name: count, dtype: Int64

In [19]:
print("Missing local authorities:", kent_clean["localAuthority"].isna().sum())

Missing local authorities: 0

In [20]:
kent_clean["localAuthority"].value_counts()

localAuthority
Kent    502
Name: count, dtype: Int64

In [21]:
kent_clean["postalAddressTownCity"].value_counts().head(30)

postalAddressTownCity
Ashford            39
Maidstone          38
Folkestone         36
Dover              33
Canterbury         31
Herne Bay          26
Margate            25
Sittingbourne      24
Tunbridge Wells    23
Deal               22
Gravesend          18
Sevenoaks          17
Dartford           16
Hythe              15
Sheerness          12
New Romney         12
Whitstable         12
Tonbridge          10
Ramsgate            8
Romney Marsh        8
Broadstairs         8
Birchington         6
Cranbrook           6
Faversham           6
Chatham             4
Edenbridge          4
Swanley             4
Staplehurst         4
Westgate On Sea     3
Greenhithe          3
Name: count, dtype: Int64

In [22]:
print("Number of unique towns/cities:",
      kent_clean["postalAddressTownCity"].nunique())

Number of unique towns/cities: 49

In [23]:
towns = sorted(kent_clean["postalAddressTownCity"].dropna().unique())

for i, town in enumerate(towns, start=1):
    print(f"{i}. {town}")

1. Ashford
2. Aylesford
3. Birchington
4. Broadstairs
5. Canterbury
6. Charing
7. Chatham
8. Cranbrook
9. Dartford
10. Deal
11. Dover
12. Edenbridge
13. Faversham
14. Folkestone
15. Gravesend
16. Greenhithe
17. Hartley
18. Herne Bay
19. Hythe
20. Hythe, Kent
21. Isle of Sheppey
22. Longfield
23. Lydd
24. Maidstone
25. Margate
26. Mersham
27. New Romney
28. Ramsgate
29. Rochester
30. Romney Marsh
31. Sandwich
32. Sellindge
33. Sevenoaks
34. Sheerness
35. Sittingbourne
36. Snodland
37. Southborough
38. Southfleet
39. Staplehurst
40. Swanley
41. Tenterden
42. Tonbridge
43. Tunbridge Wells
44. West Malling
45. Westerham
46. Westgate On Sea
47. Westgate-on-Sea
48. Westgate-on-sea
49. Whitstable

In [24]:
kent_clean["postalAddressTownCity"] = (
    kent_clean["postalAddressTownCity"]
    .astype("string")
    .str.strip()
)

kent_clean["postalAddressTownCity"] = kent_clean["postalAddressTownCity"].replace({
    "Hythe, Kent": "Hythe",
    "Westgate-on-Sea": "Westgate On Sea",
    "Westgate-on-sea": "Westgate On Sea"
})

print(
    kent_clean["postalAddressTownCity"]
    .value_counts()
    .loc[lambda x: x.index.isin(["Hythe", "Westgate On Sea"])]
)

postalAddressTownCity
Hythe              16
Westgate On Sea     7
Name: count, dtype: Int64

In [25]:
print(sorted(kent_clean["postalAddressTownCity"].dropna().unique()))

['Ashford', 'Aylesford', 'Birchington', 'Broadstairs', 'Canterbury', 'Charing', 'Chatham', 'Cranbrook', 'Dartford', 'Deal', 'Dover', 'Edenbridge', 'Faversham', 'Folkestone', 'Gravesend', 'Greenhithe', 'Hartley', 'Herne Bay', 'Hythe', 'Isle of Sheppey', 'Longfield', 'Lydd', 'Maidstone', 'Margate', 'Mersham', 'New Romney', 'Ramsgate', 'Rochester', 'Romney Marsh', 'Sandwich', 'Sellindge', 'Sevenoaks', 'Sheerness', 'Sittingbourne', 'Snodland', 'Southborough', 'Southfleet', 'Staplehurst', 'Swanley', 'Tenterden', 'Tonbridge', 'Tunbridge Wells', 'West Malling', 'Westerham', 'Westgate On Sea', 'Whitstable']

In [26]:
kent_clean["registrationDate"] = pd.to_datetime(
    kent_clean["registrationDate"],
    errors="coerce"
)

kent_clean["deregistrationDate"] = pd.to_datetime(
    kent_clean["deregistrationDate"],
    errors="coerce"
)

print(kent_clean[["registrationDate", "deregistrationDate"]].dtypes)

registrationDate      datetime64[ns]
deregistrationDate    datetime64[ns]
dtype: object

In [27]:
print("Missing registration dates:",
      kent_clean["registrationDate"].isna().sum())

print("Missing deregistration dates:",
      kent_clean["deregistrationDate"].isna().sum())

Missing registration dates: 0
Missing deregistration dates: 502

In [28]:
print(kent_clean["currentRatings.overall.rating"].value_counts(dropna=False))

currentRatings.overall.rating
Good                    263
NaN                     176
Requires improvement     49
Outstanding              14
Name: count, dtype: int64

In [29]:
print(
    "Missing ratings:",
    kent_clean["currentRatings.overall.rating"].isna().sum()
)

Missing ratings: 176

In [30]:
kent_clean["currentRatings.overall.rating"] = (
    kent_clean["currentRatings.overall.rating"]
    .fillna("Not rated")
)

print(kent_clean["currentRatings.overall.rating"].value_counts())

currentRatings.overall.rating
Good                    263
Not rated               176
Requires improvement     49
Outstanding              14
Name: count, dtype: int64

In [31]:
print(
    "Missing rating dates:",
    kent_clean["currentRatings.overall.reportDate"].isna().sum()
)

Missing rating dates: 176

In [32]:
print(kent_clean["regulatedActivities"].head(10))

2     [{'name': 'Accommodation for persons who requi...
3     [{'name': 'Accommodation for persons who requi...
4     [{'name': 'Accommodation for persons who requi...
5     [{'name': 'Accommodation for persons who requi...
7     [{'name': 'Accommodation for persons who requi...
10    [{'name': 'Accommodation for persons who requi...
13    [{'name': 'Accommodation for persons who requi...
14    [{'name': 'Accommodation for persons who requi...
18    [{'name': 'Accommodation for persons who requi...
19    [{'name': 'Accommodation for persons who requi...
Name: regulatedActivities, dtype: object

In [33]:
print(kent_clean["regulatedActivities"].isna().sum())

0

In [34]:
import ast

def get_activity_names(value):
    try:
        activities = ast.literal_eval(value) if isinstance(value, str) else value
        return [item.get("name") for item in activities if isinstance(item, dict)]
    except (ValueError, SyntaxError, TypeError):
        return []

kent_clean["activity_names"] = kent_clean["regulatedActivities"].apply(get_activity_names)

all_activities = (
    kent_clean["activity_names"]
    .explode()
    .value_counts()
)

print(all_activities)

activity_names
Accommodation for persons who require nursing or personal care    502
Treatment of disease, disorder or injury                          137
Personal care                                                      16
Diagnostic and screening procedures                                 3
Name: count, dtype: int64

In [35]:
personal_care_locations = kent_clean[
    kent_clean["activity_names"].apply(
        lambda activities: "Personal care" in activities
    )
].copy()

print("Locations with exact 'Personal care' activity:",
      len(personal_care_locations))

Locations with exact 'Personal care' activity: 16

In [36]:
print(
    personal_care_locations[
        ["locationId", "providerId", "name", "postalAddressTownCity"]
    ].head(20)
)

         locationId    providerId                     name  \
36     1-1074985387  1-1024772695              Beach House
130     1-116961317   1-101675513                Thorndene
134     1-117049912   1-101640543            Camelot Lodge
172     1-118901967   1-101703352                 Maylands
353     1-124663811   1-101654221        Harbour Care Home
483     1-128976339   1-101618185     Hale Place Farmhouse
616     1-136778918   1-120627501           Terrance House
685     1-144263091   1-101694250           Cornford House
727     1-156868778   1-101694259          Hazeldene House
809   1-20633836227  1-3932127552  Vibrant Care Home Dover
811    1-2093133330   1-483065861            Dickley Court
824    1-2153663053  1-2125701982   Ellens Court Care Home
860     1-237449361   1-214646298           Hawkinge House
998     1-419484985   1-391446222         Woodchurch House
1010   1-4488640886  1-4445093304          Hawkhurst House
1071   1-7024077970  1-5928389591         St. Helens House

     postalAddressTownCity
36             Birchington
130                  Dover
134             Folkestone
172             Whitstable
353              Herne Bay
483              Tonbridge
616                Margate
685        Tunbridge Wells
727        Tunbridge Wells
809                  Dover
811              Maidstone
824          Sittingbourne
860             Folkestone
998                Ashford
1010             Cranbrook
1071             Sheerness

In [37]:
personal_care_locations[
    [
        "name",
        "postalAddressTownCity",
        "type",
        "gacServiceTypes",
        "regulatedActivities"
    ]
].head(16)

,name,postalAddressTownCity,type,gacServiceTypes,regulatedActivities
36,Beach House,Birchington,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
130,Thorndene,Dover,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
134,Camelot Lodge,Folkestone,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
172,Maylands,Whitstable,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
353,Harbour Care Home,Herne Bay,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
483,Hale Place Farmhouse,Tonbridge,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
616,Terrance House,Margate,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
685,Cornford House,Tunbridge Wells,Social Care Org,"[{'name': 'Nursing homes', 'description': 'Car...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
727,Hazeldene House,Tunbridge Wells,Social Care Org,"[{'name': 'Community services - Nursing', 'des...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
809,Vibrant Care Home Dover,Dover,Social Care Org,"[{'name': 'Nursing homes', 'description': 'Car...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
811,Dickley Court,Maidstone,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
824,Ellens Court Care Home,Sittingbourne,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
860,Hawkinge House,Folkestone,Social Care Org,"[{'name': 'Community services - Healthcare', '...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
998,Woodchurch House,Ashford,Social Care Org,"[{'name': 'Nursing homes', 'description': 'Car...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
1010,Hawkhurst House,Cranbrook,Social Care Org,"[{'name': 'Nursing homes', 'description': 'Car...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
1071,St. Helens House,Sheerness,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."

In [38]:
personal_care_locations["gacServiceTypes"].value_counts(dropna=False)

gacServiceTypes
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                         3
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                          3
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                3
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                              1
[{'name': 'Community services - Nursing', 'description': 'Community health care services - Nurses Agency only'}, {'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported living', 'description': 'Supported living service'}]    1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                                1
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Community services - Learning disabilities', 'description': 'Community based services for people with a learning disability'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                 1
[{'name': 'Community services - Healthcare', 'description': 'Community healthcare service'}, {'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported housing', 'description': 'Extra Care housing services'}, {'name': 'Supported living', 'description': 'Supported living service'}]                              1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported housing', 'description': 'Extra Care housing services'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                       1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                 1
Name: count, dtype: int64

In [39]:
def has_homecare_service(services):
    if not isinstance(services, list):
        return False

    return any(
        isinstance(service, dict)
        and service.get("name") == "Homecare agencies"
        for service in services
    )

kent_clean["is_homecare"] = kent_clean["gacServiceTypes"].apply(
    has_homecare_service
)

print(kent_clean["is_homecare"].value_counts())

is_homecare
False    492
True      10
Name: count, dtype: int64

In [40]:
homecare_kent = kent_clean[kent_clean["is_homecare"]].copy()

print("Kent homecare locations:", len(homecare_kent))

Kent homecare locations: 10

In [41]:
homecare_kent[
    [
        "locationId",
        "providerId",
        "name",
        "postalAddressTownCity",
        "postalCode",
        "currentRatings.overall.rating"
    ]
]

,locationId,providerId,name,postalAddressTownCity,postalCode,currentRatings.overall.rating
36,1-1074985387,1-1024772695,Beach House,Birchington,CT7 9JS,Good
134,1-117049912,1-101640543,Camelot Lodge,Folkestone,CT20 2SL,Good
353,1-124663811,1-101654221,Harbour Care Home,Herne Bay,CT6 8HY,Good
483,1-128976339,1-101618185,Hale Place Farmhouse,Tonbridge,TN12 5EN,Outstanding
727,1-156868778,1-101694259,Hazeldene House,Tunbridge Wells,TN2 4AY,Good
809,1-20633836227,1-3932127552,Vibrant Care Home Dover,Dover,CT17 9JT,Not rated
824,1-2153663053,1-2125701982,Ellens Court Care Home,Sittingbourne,ME9 0NT,Good
860,1-237449361,1-214646298,Hawkinge House,Folkestone,CT18 7SS,Requires improvement
998,1-419484985,1-391446222,Woodchurch House,Ashford,TN26 3SN,Good
1071,1-7024077970,1-5928389591,St. Helens House,Sheerness,ME12 2QY,Requires improvement

In [42]:
print(
    homecare_kent[
        "currentRatings.overall.rating"
    ].value_counts(dropna=False)
)

currentRatings.overall.rating
Good                    6
Requires improvement    2
Outstanding             1
Not rated               1
Name: count, dtype: int64

# Final Kent Personal/Home Care Dataset

In [45]:
import json
import pandas as pd

with open("kent_personal_care.json", "r", encoding="utf-8") as file:
    kent_personal_care = json.load(file)

with open("medway_personal_care.json", "r", encoding="utf-8") as file:
    medway_personal_care = json.load(file)

print("Kent records:", len(kent_personal_care))
print("Medway records:", len(medway_personal_care))

Kent records: 306
Medway records: 230

In [46]:
kent_clean = pd.json_normalize(kent_personal_care)

print("Rows:", len(kent_clean))
print("Columns:", len(kent_clean.columns))

Rows: 306
Columns: 54

In [47]:
kent_clean.head(3)

,locationId,providerId,organisationType,type,name,onspdCcgCode,onspdCcgName,onspdIcbCode,onspdIcbName,odsCode,...,deregistrationDate,historicRatings,registeredManagerAbsentDate,assessmentServiceGroup,assessment,brandId,brandName,dormancyEndDate,dormancyStartDate,alsoKnownAs
0,1-10064258273,1-9491037344,Location,Social Care Org,Kent Case Management Ltd,E38000237,NHS Kent and Medway CCG,E54000032,NHS Kent and Medway Integrated Care Board,VNH6D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1-10087632956,1-6192052130,Location,Social Care Org,Royalcare- Thanet,E38000237,NHS Kent and Medway CCG,E54000032,NHS Kent and Medway Integrated Care Board,VNH6Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1-1012972951,1-935542850,Location,Social Care Org,Homecare Unique Limited,E38000237,NHS Kent and Medway CCG,E54000032,NHS Kent and Medway Integrated Care Board,NaN,...,2017-11-28,"[{'reportDate': '2015-10-07', 'reportLinkId': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
print(kent_clean.columns.tolist())

['locationId', 'providerId', 'organisationType', 'type', 'name', 'onspdCcgCode', 'onspdCcgName', 'onspdIcbCode', 'onspdIcbName', 'odsCode', 'registrationStatus', 'registrationDate', 'dormancy', 'onspdLatitude', 'onspdLongitude', 'careHome', 'inspectionDirectorate', 'postalAddressLine1', 'postalAddressLine2', 'postalAddressTownCity', 'region', 'postalCode', 'uprn', 'mainPhoneNumber', 'website', 'numberOfBeds', 'constituency', 'localAuthority', 'relationships', 'locationTypes', 'regulatedActivities', 'gacServiceTypes', 'specialisms', 'inspectionCategories', 'inspectionAreas', 'reports', 'lastInspection.date', 'lastReport.publicationDate', 'currentRatings.overall.rating', 'currentRatings.overall.reportDate', 'currentRatings.overall.reportLinkId', 'currentRatings.overall.keyQuestionRatings', 'currentRatings.reportDate', 'postalAddressCounty', 'deregistrationDate', 'historicRatings', 'registeredManagerAbsentDate', 'assessmentServiceGroup', 'assessment', 'brandId', 'brandName', 'dormancyEndDate', 'dormancyStartDate', 'alsoKnownAs']

In [49]:
print(kent_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 54 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   locationId                                 306 non-null    object
 1   providerId                                 306 non-null    object
 2   organisationType                           306 non-null    object
 3   type                                       306 non-null    object
 4   name                                       306 non-null    object
 5   onspdCcgCode                               306 non-null    object
 6   onspdCcgName                               306 non-null    object
 7   onspdIcbCode                               303 non-null    object
 8   onspdIcbName                               303 non-null    object
 9   odsCode                                    202 non-null    object
 10  registrationStatus                         306 non-null    object
 11  registrationDate                           306 non-null    object
 12  dormancy                                   306 non-null    object
 13  onspdLatitude                              306 non-null    float64
 14  onspdLongitude                             306 non-null    float64
 15  careHome                                   306 non-null    object
 16  inspectionDirectorate                      306 non-null    object
 17  postalAddressLine1                         306 non-null    object
 18  postalAddressLine2                         201 non-null    object
 19  postalAddressTownCity                      306 non-null    object
 20  region                                     306 non-null    object
 21  postalCode                                 306 non-null    object
 22  uprn                                       183 non-null    object
 23  mainPhoneNumber                            281 non-null    object
 24  website                                    200 non-null    object
 25  numberOfBeds                               294 non-null    float64
 26  constituency                               306 non-null    object
 27  localAuthority                             306 non-null    object
 28  relationships                              306 non-null    object
 29  locationTypes                              306 non-null    object
 30  regulatedActivities                        306 non-null    object
 31  gacServiceTypes                            306 non-null    object
 32  specialisms                                306 non-null    object
 33  inspectionCategories                       264 non-null    object
 34  inspectionAreas                            306 non-null    object
 35  reports                                    206 non-null    object
 36  lastInspection.date                        207 non-null    object
 37  lastReport.publicationDate                 163 non-null    object
 38  currentRatings.overall.rating              197 non-null    object
 39  currentRatings.overall.reportDate          150 non-null    object
 40  currentRatings.overall.reportLinkId        150 non-null    object
 41  currentRatings.overall.keyQuestionRatings  197 non-null    object
 42  currentRatings.reportDate                  150 non-null    object
 43  postalAddressCounty                        159 non-null    object
 44  deregistrationDate                         178 non-null    object
 45  historicRatings                            86 non-null     object
 46  registeredManagerAbsentDate                16 non-null     object
 47  assessmentServiceGroup                     19 non-null     object
 48  assessment                                 19 non-null     object
 49  brandId                                    78 non-null     object
 50  brandName                                  78 non-null     object
 51  dormancyEndDate                            39 non-null     object
 52  dormancyStartDate                          25 non-null     object
 53  alsoKnownAs                                8 non-null      object
dtypes: float64(3), object(51)
memory usage: 129.2+ KB
None

In [50]:
print("Duplicate location IDs:",
      kent_clean["locationId"].duplicated().sum())

print("Duplicate provider IDs:",
      kent_clean["providerId"].duplicated().sum())

Duplicate location IDs: 0
Duplicate provider IDs: 57

In [51]:
print(kent_clean["registrationStatus"].value_counts(dropna=False))

registrationStatus
Deregistered    178
Registered      128
Name: count, dtype: int64

In [53]:
print("Missing postcodes:",
      kent_clean["postalCode"].isna().sum())

print("Missing local authorities:",
      kent_clean["localAuthority"].isna().sum())

Missing postcodes: 0
Missing local authorities: 0

In [55]:
kent_registered = kent_clean[
    kent_clean["registrationStatus"].str.strip().str.lower() == "registered"
].copy()

print("Registered Kent locations:", len(kent_registered))

Registered Kent locations: 128

In [56]:
print(
    kent_registered["currentRatings.overall.rating"]
    .value_counts(dropna=False)
)

currentRatings.overall.rating
Good                    80
NaN                     31
Requires improvement    16
Outstanding              1
Name: count, dtype: int64

In [57]:
kent_registered["currentRatings.overall.rating"] = (
    kent_registered["currentRatings.overall.rating"]
    .fillna("Not rated")
)

print(
    kent_registered["currentRatings.overall.rating"]
    .value_counts()
)

currentRatings.overall.rating
Good                    80
Not rated               31
Requires improvement    16
Outstanding              1
Name: count, dtype: int64

In [58]:
kent_registered["postalCode"] = (
    kent_registered["postalCode"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

In [59]:
print("Missing postcodes:", kent_registered["postalCode"].isna().sum())

Missing postcodes: 0

In [63]:
town_counts = kent_registered["postalAddressTownCity"].value_counts()

print(town_counts)

postalAddressTownCity
Dartford           16
Ashford            12
Maidstone          11
Gravesend          10
Dover               6
Canterbury          5
Sittingbourne       5
Folkestone          5
Whitstable          4
Herne Bay           4
Tunbridge Wells     4
Margate             4
Sheerness           3
Faversham           3
Longfield           3
Deal                3
Tonbridge           3
Ramsgate            2
Birchington         2
Cranbrook           2
Broadstairs         2
Hythe               2
West Malling        2
Sevenoaks           2
Aylesford           2
Swanley             2
Cowden              1
Snodland            1
Speldhurst          1
Westerham           1
Rochester           1
Tenterden           1
Westgate On Sea     1
Greenhithe          1
Sandwich            1
Name: count, dtype: Int64

In [64]:
print("Unique towns:", kent_registered["postalAddressTownCity"].nunique())

Unique towns: 35

In [62]:
kent_registered["postalAddressTownCity"] = (
    kent_registered["postalAddressTownCity"]
    .astype("string")
    .str.strip()
)

kent_registered["postalAddressTownCity"] = kent_registered[
    "postalAddressTownCity"
].replace({
    "Westgate-on-sea": "Westgate On Sea"
})

In [67]:
print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Westgate", case=False, na=False)
    ]["postalAddressTownCity"].value_counts()
)

postalAddressTownCity
Westgate On Sea    1
Name: count, dtype: Int64

In [68]:
print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Hythe", case=False, na=False)
    ]["postalAddressTownCity"].value_counts()
)

postalAddressTownCity
Hythe    2
Name: count, dtype: Int64

In [69]:
print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Westgate", case=False, na=False)
    ]["postalAddressTownCity"].unique()
)

print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Hythe", case=False, na=False)
    ]["postalAddressTownCity"].unique()
)

<StringArray>
['Westgate On Sea']
Length: 1, dtype: string
<StringArray>
['Hythe']
Length: 1, dtype: string

In [70]:
print("Missing registration dates:",
      kent_registered["registrationDate"].isna().sum())

print("Missing rating dates:",
      kent_registered["currentRatings.overall.reportDate"].isna().sum())

Missing registration dates: 0
Missing rating dates: 31

In [71]:
print(
    kent_registered["currentRatings.overall.rating"]
    .value_counts(dropna=False)
)

currentRatings.overall.rating
Good                    80
Not rated               31
Requires improvement    16
Outstanding              1
Name: count, dtype: int64

In [72]:
print("Duplicate location IDs:",
      kent_registered["locationId"].duplicated().sum())

Duplicate location IDs: 0

In [73]:
final_columns = [
    "locationId",
    "providerId",
    "name",
    "registrationStatus",
    "registrationDate",
    "postalAddressLine1",
    "postalAddressTownCity",
    "postalAddressCounty",
    "region",
    "postalCode",
    "mainPhoneNumber",
    "localAuthority",
    "numberOfBeds",
    "currentRatings.overall.rating",
    "currentRatings.overall.reportDate",
    "regulatedActivities",
    "gacServiceTypes"
]

kent_final = kent_registered[final_columns].copy()

print("Final rows:", len(kent_final))
print("Final columns:", len(kent_final.columns))

Final rows: 128
Final columns: 17

In [74]:
kent_final.head()

,locationId,providerId,name,registrationStatus,registrationDate,postalAddressLine1,postalAddressTownCity,postalAddressCounty,region,postalCode,mainPhoneNumber,localAuthority,numberOfBeds,currentRatings.overall.rating,currentRatings.overall.reportDate,regulatedActivities,gacServiceTypes
0,1-10064258273,1-9491037344,Kent Case Management Ltd,Registered,2020-12-30,"The Stables, Bradbourne House,",West Malling,NaN,South East,ME19 6DZ,07741497668,Kent,0.0,Good,2022-03-18,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."
1,1-10087632956,1-6192052130,Royalcare- Thanet,Registered,2020-12-23,Kent Innovation Centre,Broadstairs,Kent,South East,CT10 2QQ,01843838122,Kent,0.0,Requires improvement,2022-05-25,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."
3,1-10200463066,1-3982604534,PCAS Kent Ltd,Registered,2021-01-14,Unit 5,Faversham,NaN,South East,ME13 8GD,03300535919,Kent,0.0,Not rated,NaN,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."
4,1-10204301199,1-118164017,Priory Supported Living Kent,Registered,2021-02-25,Buckland,Dover,NaN,South East,CT17 0TQ,01304202010,Kent,0.0,Good,2022-11-11,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."
5,1-10212079624,1-102643252,SeeAbility - Kent Supported Living,Registered,2021-01-14,Laburnum House,Birchington,NaN,South East,CT7 9DQ,07725424042,Kent,0.0,Good,2022-07-01,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."

In [75]:
kent_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128 entries, 0 to 303
Data columns (total 17 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   locationId                         128 non-null    object
 1   providerId                         128 non-null    object
 2   name                               128 non-null    object
 3   registrationStatus                 128 non-null    object
 4   registrationDate                   128 non-null    object
 5   postalAddressLine1                 128 non-null    object
 6   postalAddressTownCity              128 non-null    string
 7   postalAddressCounty                34 non-null     object
 8   region                             128 non-null    object
 9   postalCode                         128 non-null    string
 10  mainPhoneNumber                    116 non-null    object
 11  localAuthority                     128 non-null    object
 12  numberOfBeds                       125 non-null    float64
 13  currentRatings.overall.rating      128 non-null    object
 14  currentRatings.overall.reportDate  97 non-null     object
 15  regulatedActivities                128 non-null    object
 16  gacServiceTypes                    128 non-null    object
dtypes: float64(1), object(14), string(2)
memory usage: 18.0+ KB

In [76]:
kent_final.to_csv(
    "kent_personal_homecare_clean.csv",
    index=False
)

print("CSV created successfully!")

CSV created successfully!