In [1]:
import json
import pandas as pd

with open("kent_care_homes.json", "r", encoding="utf-8") as file:
    kent_care_homes = json.load(file)

with open("medway_care_homes.json", "r", encoding="utf-8") as file:
    medway_care_homes = json.load(file)

print("Kent records:", len(kent_care_homes))
print("Medway records:", len(medway_care_homes))

Kent records: 3730
Medway records: 655

In [2]:
kent_df = pd.json_normalize(kent_care_homes)
medway_df = pd.json_normalize(medway_care_homes)

print("Kent shape:", kent_df.shape)
print("Medway shape:", medway_df.shape)

Kent shape: (3730, 59)
Medway shape: (655, 59)

In [3]:
print(kent_df.columns.tolist())

['locationId', 'providerId', 'organisationType', 'type', 'name', 'brandId', 'brandName', 'onspdCcgCode', 'onspdCcgName', 'onspdIcbCode', 'onspdIcbName', 'registrationStatus', 'registrationDate', 'deregistrationDate', 'dormancy', 'onspdLatitude', 'onspdLongitude', 'careHome', 'inspectionDirectorate', 'postalAddressLine1', 'postalAddressLine2', 'postalAddressTownCity', 'postalAddressCounty', 'region', 'postalCode', 'uprn', 'mainPhoneNumber', 'website', 'numberOfBeds', 'constituency', 'localAuthority', 'relationships', 'locationTypes', 'regulatedActivities', 'gacServiceTypes', 'specialisms', 'inspectionCategories', 'inspectionAreas', 'reports', 'lastInspection.date', 'lastReport.publicationDate', 'currentRatings.overall.rating', 'currentRatings.overall.reportDate', 'currentRatings.overall.reportLinkId', 'currentRatings.overall.keyQuestionRatings', 'currentRatings.reportDate', 'currentRatings.serviceRatings', 'odsCcgCode', 'odsCcgName', 'odsCode', 'historicRatings', 'assessmentServiceGroup', 'assessment', 'dormancyEndDate', 'registeredManagerAbsentDate', 'alsoKnownAs', 'dormancyStartDate', 'unpublishedReports', 'providerInspectionAreas']

In [4]:
kent_df.head(3)

,locationId,providerId,organisationType,type,name,brandId,brandName,onspdCcgCode,onspdCcgName,onspdIcbCode,...,odsCode,historicRatings,assessmentServiceGroup,assessment,dormancyEndDate,registeredManagerAbsentDate,alsoKnownAs,dormancyStartDate,unpublishedReports,providerInspectionAreas
0,1-1001764512,1-983441221,Location,Independent Healthcare Org,Optical Express - Bluewater Clinic,BD142,BRAND Optical Express,E38000237,NHS Kent and Medway CCG,E54000032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1-1002113960,1-942188853,Location,Social Care Org,Elmwood,NaN,NaN,E38000237,NHS Kent and Medway CCG,E54000032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1-10048396988,1-9931659218,Location,Primary Medical Services,Harbour Medical Practice,NaN,NaN,E38000237,NHS Kent and Medway CCG,E54000032,...,G82217,"[{'reportDate': '2017-08-07', 'reportLinkId': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
kent_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3730 entries, 0 to 3729
Data columns (total 59 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   locationId                                 3730 non-null   object
 1   providerId                                 3730 non-null   object
 2   organisationType                           3730 non-null   object
 3   type                                       3730 non-null   object
 4   name                                       3730 non-null   object
 5   brandId                                    1203 non-null   object
 6   brandName                                  1203 non-null   object
 7   onspdCcgCode                               3724 non-null   object
 8   onspdCcgName                               3724 non-null   object
 9   onspdIcbCode                               3690 non-null   object
 10  onspdIcbName                               3690 non-null   object
 11  registrationStatus                         3730 non-null   object
 12  registrationDate                           3730 non-null   object
 13  deregistrationDate                         2054 non-null   object
 14  dormancy                                   3730 non-null   object
 15  onspdLatitude                              3729 non-null   float64
 16  onspdLongitude                             3729 non-null   float64
 17  careHome                                   3730 non-null   object
 18  inspectionDirectorate                      3730 non-null   object
 19  postalAddressLine1                         3730 non-null   object
 20  postalAddressLine2                         2007 non-null   object
 21  postalAddressTownCity                      3730 non-null   object
 22  postalAddressCounty                        2854 non-null   object
 23  region                                     3730 non-null   object
 24  postalCode                                 3730 non-null   object
 25  uprn                                       2365 non-null   object
 26  mainPhoneNumber                            3401 non-null   object
 27  website                                    2121 non-null   object
 28  numberOfBeds                               3567 non-null   float64
 29  constituency                               3730 non-null   object
 30  localAuthority                             3730 non-null   object
 31  relationships                              3730 non-null   object
 32  locationTypes                              3730 non-null   object
 33  regulatedActivities                        3730 non-null   object
 34  gacServiceTypes                            3730 non-null   object
 35  specialisms                                3730 non-null   object
 36  inspectionCategories                       3244 non-null   object
 37  inspectionAreas                            3730 non-null   object
 38  reports                                    2338 non-null   object
 39  lastInspection.date                        2352 non-null   object
 40  lastReport.publicationDate                 1817 non-null   object
 41  currentRatings.overall.rating              2252 non-null   object
 42  currentRatings.overall.reportDate          1592 non-null   object
 43  currentRatings.overall.reportLinkId        1592 non-null   object
 44  currentRatings.overall.keyQuestionRatings  2252 non-null   object
 45  currentRatings.reportDate                  1616 non-null   object
 46  currentRatings.serviceRatings              279 non-null    object
 47  odsCcgCode                                 306 non-null    object
 48  odsCcgName                                 305 non-null    object
 49  odsCode                                    2076 non-null   object
 50  historicRatings                            1176 non-null   object
 51  assessmentServiceGroup                     284 non-null    object
 52  assessment                                 284 non-null    object
 53  dormancyEndDate                            260 non-null    object
 54  registeredManagerAbsentDate                133 non-null    object
 55  alsoKnownAs                                158 non-null    object
 56  dormancyStartDate                          106 non-null    object
 57  unpublishedReports                         22 non-null     object
 58  providerInspectionAreas                    26 non-null     object
dtypes: float64(3), object(56)
memory usage: 1.7+ MB

In [6]:
missing = kent_df.isna().sum()

print(missing[missing > 0].sort_values(ascending=False))

unpublishedReports                           3708
providerInspectionAreas                      3704
dormancyStartDate                            3624
registeredManagerAbsentDate                  3597
alsoKnownAs                                  3572
dormancyEndDate                              3470
currentRatings.serviceRatings                3451
assessment                                   3446
assessmentServiceGroup                       3446
odsCcgName                                   3425
odsCcgCode                                   3424
historicRatings                              2554
brandId                                      2527
brandName                                    2527
currentRatings.overall.reportDate            2138
currentRatings.overall.reportLinkId          2138
currentRatings.reportDate                    2114
lastReport.publicationDate                   1913
postalAddressLine2                           1723
deregistrationDate                           1676
odsCode                                      1654
website                                      1609
currentRatings.overall.rating                1478
currentRatings.overall.keyQuestionRatings    1478
reports                                      1392
lastInspection.date                          1378
uprn                                         1365
postalAddressCounty                           876
inspectionCategories                          486
mainPhoneNumber                               329
numberOfBeds                                  163
onspdIcbCode                                   40
onspdIcbName                                   40
onspdCcgName                                    6
onspdCcgCode                                    6
onspdLongitude                                  1
onspdLatitude                                   1
dtype: int64

In [7]:
for i, col in enumerate(kent_df.columns, start=1):
    print(f"{i}. {col}")

1. locationId
2. providerId
3. organisationType
4. type
5. name
6. brandId
7. brandName
8. onspdCcgCode
9. onspdCcgName
10. onspdIcbCode
11. onspdIcbName
12. registrationStatus
13. registrationDate
14. deregistrationDate
15. dormancy
16. onspdLatitude
17. onspdLongitude
18. careHome
19. inspectionDirectorate
20. postalAddressLine1
21. postalAddressLine2
22. postalAddressTownCity
23. postalAddressCounty
24. region
25. postalCode
26. uprn
27. mainPhoneNumber
28. website
29. numberOfBeds
30. constituency
31. localAuthority
32. relationships
33. locationTypes
34. regulatedActivities
35. gacServiceTypes
36. specialisms
37. inspectionCategories
38. inspectionAreas
39. reports
40. lastInspection.date
41. lastReport.publicationDate
42. currentRatings.overall.rating
43. currentRatings.overall.reportDate
44. currentRatings.overall.reportLinkId
45. currentRatings.overall.keyQuestionRatings
46. currentRatings.reportDate
47. currentRatings.serviceRatings
48. odsCcgCode
49. odsCcgName
50. odsCode
51. historicRatings
52. assessmentServiceGroup
53. assessment
54. dormancyEndDate
55. registeredManagerAbsentDate
56. alsoKnownAs
57. dormancyStartDate
58. unpublishedReports
59. providerInspectionAreas

In [8]:
print("Registration status:")
print(kent_df["registrationStatus"].value_counts(dropna=False))

print("\nCare home:")
print(kent_df["careHome"].value_counts(dropna=False))

print("\nOrganisation type:")
print(kent_df["organisationType"].value_counts(dropna=False))

print("\nDuplicate location IDs:")
print(kent_df["locationId"].duplicated().sum())

print("\nDuplicate provider IDs:")
print(kent_df["providerId"].duplicated().sum())

Registration status:
registrationStatus
Deregistered    2054
Registered      1676
Name: count, dtype: int64

Care home:
careHome
N    2607
Y    1123
Name: count, dtype: int64

Organisation type:
organisationType
Location    3730
Name: count, dtype: int64

Duplicate location IDs:
0

Duplicate provider IDs:
1423

In [9]:
kent_df.groupby("registrationStatus")[[
    "locationId",
    "providerId",
    "name",
    "postalCode",
    "registrationDate",
    "deregistrationDate"
]].head(3)

,locationId,providerId,name,postalCode,registrationDate,deregistrationDate
0,1-1001764512,1-983441221,Optical Express - Bluewater Clinic,DA9 9SJ,2013-10-14,2020-07-01
1,1-1002113960,1-942188853,Elmwood,ME15 7DR,2013-11-26,2014-12-19
2,1-10048396988,1-9931659218,Harbour Medical Practice,CT20 1JY,2021-03-24,NaN
3,1-10053866949,1-9703551783,Southbank Dental Practice,CT10 1JB,2021-02-03,2021-07-29
4,1-10064258273,1-9491037344,Kent Case Management Ltd,ME19 6DZ,2020-12-30,NaN
5,1-10087632956,1-6192052130,Royalcare- Thanet,CT10 2QQ,2020-12-23,NaN

In [10]:
kent_clean = kent_df[
    kent_df["registrationStatus"].str.strip().str.lower() == "registered"
].copy()

print("Original Kent records:", len(kent_df))
print("Registered Kent records:", len(kent_clean))

Original Kent records: 3730
Registered Kent records: 1676

In [11]:
kent_clean["registrationStatus"].value_counts()

registrationStatus
Registered    1676
Name: count, dtype: int64

In [12]:
text_columns = [
    "name",
    "registrationStatus",
    "organisationType",
    "postalAddressTownCity",
    "postalAddressCounty",
    "region",
    "postalCode",
    "localAuthority"
]

for col in text_columns:
    if col in kent_clean.columns:
        kent_clean[col] = kent_clean[col].astype("string").str.strip()

In [13]:
print(kent_clean["postalCode"].head(10))

2     CT20 1JY
4     ME19 6DZ
5     CT10 2QQ
7     TN24 9BP
8     TN26 2AF
10    TN29 9DQ
11    DA12 2NQ
13    ME14 5SF
14    ME13 8GD
15    CT17 0TQ
Name: postalCode, dtype: string

In [14]:
print("Missing postcodes:", kent_clean["postalCode"].isna().sum())

Missing postcodes: 0

In [15]:
kent_clean["postalCode"] = (
    kent_clean["postalCode"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

print(kent_clean["postalCode"].head(10))

2     CT20 1JY
4     ME19 6DZ
5     CT10 2QQ
7     TN24 9BP
8     TN26 2AF
10    TN29 9DQ
11    DA12 2NQ
13    ME14 5SF
14    ME13 8GD
15    CT17 0TQ
Name: postalCode, dtype: string

In [16]:
print("Duplicate postcodes:", kent_clean["postalCode"].duplicated().sum())

Duplicate postcodes: 374

In [17]:
print(kent_clean["localAuthority"].value_counts(dropna=False))

localAuthority
Kent    1676
Name: count, dtype: Int64

In [18]:
print("Missing local authorities:", kent_clean["localAuthority"].isna().sum())

Missing local authorities: 0

In [19]:
kent_clean["localAuthority"].value_counts()

localAuthority
Kent    1676
Name: count, dtype: Int64

In [20]:
kent_clean["postalAddressTownCity"].value_counts().head(30)

postalAddressTownCity
Maidstone          166
Ashford            133
Dartford           121
Canterbury         120
Tunbridge Wells    105
Gravesend           87
Sittingbourne       80
Folkestone          73
Sevenoaks           70
Dover               68
Tonbridge           63
Margate             57
Herne Bay           48
Deal                47
Sheerness           37
Whitstable          33
Ramsgate            32
West Malling        28
Hythe               26
Broadstairs         24
Faversham           23
Cranbrook           21
New Romney          19
Swanley             17
Aylesford           15
Romney Marsh        13
Tenterden           12
Longfield           12
Sandwich            12
Greenhithe          11
Name: count, dtype: Int64

In [21]:
print("Number of unique towns/cities:",
      kent_clean["postalAddressTownCity"].nunique())

Number of unique towns/cities: 64

In [22]:
towns = sorted(kent_clean["postalAddressTownCity"].dropna().unique())

for i, town in enumerate(towns, start=1):
    print(f"{i}. {town}")

1. Ashford
2. Aylesford
3. Birchington
4. Borough Green
5. Brenchley
6. Broadstairs
7. Canterbury
8. Charing
9. Chatham
10. Cowden
11. Cranbrook
12. Dartford
13. Deal
14. Dover
15. Edenbridge
16. Faversham
17. Folkestone
18. Gravesend
19. Greenhithe
20. Hartley
21. Hawkhurst
22. Herne Bay
23. Hernebay
24. Hythe
25. Hythe, Kent
26. Isle of Sheppey
27. Isle of Sheppy
28. Kent
29. Longfield
30. Lydd
31. Maidstone
32. Margate
33. Medway
34. Mersham
35. New Romney
36. Northfleet
37. Nr Bearsted
38. Queenborough
39. Ramsgate
40. Rochester
41. Romney Marsh
42. Sandwich
43. Sellindge
44. Sevenoaks
45. Sheerness
46. Sittingbourne
47. Snodland
48. Southborough
49. Southfleet
50. Speldhurst
51. Staplehurst
52. Swanley
53. Swanscombe
54. Tenterden
55. Tonbridge
56. Tunbridge Wells
57. West Malling
58. Westerham
59. Westgate On Sea
60. Westgate-on-Sea
61. Westgate-on-sea
62. Whitstable
63. Willesborough
64. Wye

In [23]:
kent_clean["postalAddressTownCity"] = (
    kent_clean["postalAddressTownCity"]
    .astype("string")
    .str.strip()
)

kent_clean["postalAddressTownCity"] = kent_clean["postalAddressTownCity"].replace({
    "Hythe, Kent": "Hythe",
    "Westgate-on-Sea": "Westgate On Sea",
    "Westgate-on-sea": "Westgate On Sea"
})

print(
    kent_clean["postalAddressTownCity"]
    .value_counts()
    .loc[lambda x: x.index.isin(["Hythe", "Westgate On Sea"])]
)

postalAddressTownCity
Hythe              27
Westgate On Sea    12
Name: count, dtype: Int64

In [24]:
print(sorted(kent_clean["postalAddressTownCity"].dropna().unique()))

['Ashford', 'Aylesford', 'Birchington', 'Borough Green', 'Brenchley', 'Broadstairs', 'Canterbury', 'Charing', 'Chatham', 'Cowden', 'Cranbrook', 'Dartford', 'Deal', 'Dover', 'Edenbridge', 'Faversham', 'Folkestone', 'Gravesend', 'Greenhithe', 'Hartley', 'Hawkhurst', 'Herne Bay', 'Hernebay', 'Hythe', 'Isle of Sheppey', 'Isle of Sheppy', 'Kent', 'Longfield', 'Lydd', 'Maidstone', 'Margate', 'Medway', 'Mersham', 'New Romney', 'Northfleet', 'Nr Bearsted', 'Queenborough', 'Ramsgate', 'Rochester', 'Romney Marsh', 'Sandwich', 'Sellindge', 'Sevenoaks', 'Sheerness', 'Sittingbourne', 'Snodland', 'Southborough', 'Southfleet', 'Speldhurst', 'Staplehurst', 'Swanley', 'Swanscombe', 'Tenterden', 'Tonbridge', 'Tunbridge Wells', 'West Malling', 'Westerham', 'Westgate On Sea', 'Whitstable', 'Willesborough', 'Wye']

In [25]:
kent_clean["registrationDate"] = pd.to_datetime(
    kent_clean["registrationDate"],
    errors="coerce"
)

kent_clean["deregistrationDate"] = pd.to_datetime(
    kent_clean["deregistrationDate"],
    errors="coerce"
)

print(kent_clean[["registrationDate", "deregistrationDate"]].dtypes)

registrationDate      datetime64[ns]
deregistrationDate    datetime64[ns]
dtype: object

In [26]:
print("Missing registration dates:",
      kent_clean["registrationDate"].isna().sum())

print("Missing deregistration dates:",
      kent_clean["deregistrationDate"].isna().sum())

Missing registration dates: 0
Missing deregistration dates: 1676

In [27]:
print(kent_clean["currentRatings.overall.rating"].value_counts(dropna=False))

currentRatings.overall.rating
NaN                        728
Good                       575
Inspected but not rated    180
Requires improvement        86
No published rating         72
Outstanding                 35
Name: count, dtype: int64

In [28]:
print(
    "Missing ratings:",
    kent_clean["currentRatings.overall.rating"].isna().sum()
)

Missing ratings: 728

In [29]:
kent_clean["currentRatings.overall.rating"] = (
    kent_clean["currentRatings.overall.rating"]
    .fillna("Not rated")
)

print(kent_clean["currentRatings.overall.rating"].value_counts())

currentRatings.overall.rating
Not rated                  728
Good                       575
Inspected but not rated    180
Requires improvement        86
No published rating         72
Outstanding                 35
Name: count, dtype: int64

In [30]:
print(
    "Missing rating dates:",
    kent_clean["currentRatings.overall.reportDate"].isna().sum()
)

Missing rating dates: 800

In [31]:
print(kent_clean["regulatedActivities"].head(10))

2     [{'name': 'Maternity and midwifery services', ...
4     [{'name': 'Personal care', 'code': 'RA1', 'con...
5     [{'name': 'Personal care', 'code': 'RA1', 'con...
7     [{'name': 'Accommodation for persons who requi...
8     [{'name': 'Accommodation for persons who requi...
10    [{'name': 'Treatment of disease, disorder or i...
11    [{'name': 'Treatment of disease, disorder or i...
13    [{'name': 'Treatment of disease, disorder or i...
14    [{'name': 'Personal care', 'code': 'RA1', 'con...
15    [{'name': 'Personal care', 'code': 'RA1', 'con...
Name: regulatedActivities, dtype: object

In [32]:
print(kent_clean["regulatedActivities"].isna().sum())

0

In [33]:
import ast

def get_activity_names(value):
    try:
        activities = ast.literal_eval(value) if isinstance(value, str) else value
        return [item.get("name") for item in activities if isinstance(item, dict)]
    except (ValueError, SyntaxError, TypeError):
        return []

kent_clean["activity_names"] = kent_clean["regulatedActivities"].apply(get_activity_names)

all_activities = (
    kent_clean["activity_names"]
    .explode()
    .value_counts()
)

print(all_activities)

activity_names
Treatment of disease, disorder or injury                                                 875
Diagnostic and screening procedures                                                      646
Surgical procedures                                                                      559
Accommodation for persons who require nursing or personal care                           502
Personal care                                                                            457
Family planning                                                                          153
Maternity and midwifery services                                                         150
Assessment or medical treatment for persons detained under the Mental Health Act 1983     25
Transport services, triage and medical advice provided remotely                           20
Services in slimming clinics                                                               6
Termination of pregnancies                                                                 6
Nursing care                                                                               4
Management of supply of blood and blood derived products                                   4
Accommodation for persons who require treatment for substance misuse                       3
Name: count, dtype: int64

In [34]:
personal_care_locations = kent_clean[
    kent_clean["activity_names"].apply(
        lambda activities: "Personal care" in activities
    )
].copy()

print("Locations with exact 'Personal care' activity:",
      len(personal_care_locations))

Locations with exact 'Personal care' activity: 457

In [35]:
print(
    personal_care_locations[
        ["locationId", "providerId", "name", "postalAddressTownCity"]
    ].head(20)
)

        locationId     providerId                                name  \
4    1-10064258273   1-9491037344            Kent Case Management Ltd
5    1-10087632956   1-6192052130                   Royalcare- Thanet
14   1-10200463066   1-3982604534                       PCAS Kent Ltd
15   1-10204301199    1-118164017        Priory Supported Living Kent
17   1-10212079624    1-102643252  SeeAbility - Kent Supported Living
26   1-10336570859   1-9718215831                    Devoted Homecare
33   1-10409575620   1-7187418734           Glorycrown Healthcare Ltd
40     1-104968428    1-101625791                     Marbleside Care
47   1-10535587136   1-8660052839               Henderson Health Care
49    1-1054132568    1-979719472           Figtree Care Services Ltd
59   1-10631096735   1-9773563733          Simplex Healthcare Limited
73   1-10675883005   1-9621815588                Greener Pastures Ltd
84   1-10724452227   1-9833333349           Elizabeths Rose Home Care
87     1-107292415    1-101703451                        Welcome Home
94    1-1074985387   1-1024772695                         Beach House
99   1-10757577665   1-9929887255  Zander Mackenzie Care U.K. Limited
108  1-10841906240  1-10678452104                          Head First
122  1-10882613597    1-118166337         Endurance Kent- Broadstairs
132  1-10984191735   1-2186667355    Longfield Integrated Care Centre
160    1-112047455    1-101642389                   TerraBlu Homecare

    postalAddressTownCity
4            West Malling
5             Broadstairs
14              Faversham
15                  Dover
17            Birchington
26                Ashford
33              Maidstone
40                Margate
47           West Malling
49               Dartford
59          Sittingbourne
73              Gravesend
84              Maidstone
87              Sheerness
94            Birchington
99               Dartford
108             Cranbrook
122           Broadstairs
132             Longfield
160       Tunbridge Wells

In [36]:
personal_care_locations[
    [
        "name",
        "postalAddressTownCity",
        "type",
        "gacServiceTypes",
        "regulatedActivities"
    ]
].head(16)

,name,postalAddressTownCity,type,gacServiceTypes,regulatedActivities
4,Kent Case Management Ltd,West Malling,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
5,Royalcare- Thanet,Broadstairs,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
14,PCAS Kent Ltd,Faversham,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
15,Priory Supported Living Kent,Dover,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
17,SeeAbility - Kent Supported Living,Birchington,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
26,Devoted Homecare,Ashford,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
33,Glorycrown Healthcare Ltd,Maidstone,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
40,Marbleside Care,Margate,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
47,Henderson Health Care,West Malling,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
49,Figtree Care Services Ltd,Dartford,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
59,Simplex Healthcare Limited,Sittingbourne,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
73,Greener Pastures Ltd,Gravesend,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
84,Elizabeths Rose Home Care,Maidstone,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
87,Welcome Home,Sheerness,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
94,Beach House,Birchington,Social Care Org,"[{'name': 'Residential homes', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."
99,Zander Mackenzie Care U.K. Limited,Dartford,Social Care Org,"[{'name': 'Homecare agencies', 'description': ...","[{'name': 'Personal care', 'code': 'RA1', 'con..."

In [37]:
personal_care_locations["gacServiceTypes"].value_counts(dropna=False)

gacServiceTypes
[{'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               296
[{'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       95
[{'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 32
[{'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported housing', 'description': 'Extra Care housing services'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    7
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                     3
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3
[{'name': 'Shared lives', 'description': 'Shared Lives'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  2
[{'name': 'Community services - Nursing', 'description': 'Community health care services - Nurses Agency only'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2
[{'name': 'Community services - Nursing', 'description': 'Community health care services - Nurses Agency only'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Rehabilitation (illness/injury)', 'description': 'Rehabilitation services'}]                                                                                                                                                                                                                                                                                                                                                                          1
[{'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Doctors/Gps', 'description': 'Doctors consultation service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
[{'name': 'Supported housing', 'description': 'Extra Care housing services'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
[{'name': 'Community services - Nursing', 'description': 'Community health care services - Nurses Agency only'}, {'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                         1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                   1
[{'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Community services - Learning disabilities', 'description': 'Community based services for people with a learning disability'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                      1
[{'name': 'Community services - Healthcare', 'description': 'Community healthcare service'}, {'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported housing', 'description': 'Extra Care housing services'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                   1
[{'name': 'Community services - Healthcare', 'description': 'Community healthcare service'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Residential homes', 'description': 'Care home service without nursing'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Supported housing', 'description': 'Extra Care housing services'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                            1
[{'name': 'Nursing homes', 'description': 'Care home service with nursing'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
[{'name': 'Community services - Mental Health', 'description': 'Community based services for people with mental health needs'}, {'name': 'Shared lives', 'description': 'Shared Lives'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
[{'name': 'Community services - Healthcare', 'description': 'Community healthcare service'}, {'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Community services - Learning disabilities', 'description': 'Community based services for people with a learning disability'}, {'name': 'Community services - Mental Health', 'description': 'Community based services for people with mental health needs'}, {'name': 'Supported living', 'description': 'Supported living service'}, {'name': 'Community services - Substance abuse', 'description': 'Community based services for people who misuse substances'}]      1
[{'name': 'Homecare agencies', 'description': 'Domiciliary care service'}, {'name': 'Shared lives', 'description': 'Shared Lives'}, {'name': 'Supported living', 'description': 'Supported living service'}]                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Name: count, dtype: int64

In [38]:
def has_homecare_service(services):
    if not isinstance(services, list):
        return False

    return any(
        isinstance(service, dict)
        and service.get("name") == "Homecare agencies"
        for service in services
    )

kent_clean["is_homecare"] = kent_clean["gacServiceTypes"].apply(
    has_homecare_service
)

print(kent_clean["is_homecare"].value_counts())

is_homecare
False    1261
True      415
Name: count, dtype: int64

In [39]:
homecare_kent = kent_clean[kent_clean["is_homecare"]].copy()

print("Kent homecare locations:", len(homecare_kent))

Kent homecare locations: 415

In [40]:
homecare_kent[
    [
        "locationId",
        "providerId",
        "name",
        "postalAddressTownCity",
        "postalCode",
        "currentRatings.overall.rating"
    ]
]

,locationId,providerId,name,postalAddressTownCity,postalCode,currentRatings.overall.rating
4,1-10064258273,1-9491037344,Kent Case Management Ltd,West Malling,ME19 6DZ,Good
5,1-10087632956,1-6192052130,Royalcare- Thanet,Broadstairs,CT10 2QQ,Requires improvement
14,1-10200463066,1-3982604534,PCAS Kent Ltd,Faversham,ME13 8GD,Not rated
15,1-10204301199,1-118164017,Priory Supported Living Kent,Dover,CT17 0TQ,Good
17,1-10212079624,1-102643252,SeeAbility - Kent Supported Living,Birchington,CT7 9DQ,Good
...,...,...,...,...,...,...
3558,1-9749225981,1-710829848,MidCo Care Kent,Tunbridge Wells,TN4 8BS,Good
3570,1-9829482322,1-9226393522,Rusko Care Ltd,Canterbury,CT4 5DE,Good
3571,1-9838801116,1-9156191215,Avengers Prime Care,Ashford,TN27 9TN,Not rated
3574,1-990223635,1-315809199,The Garden of Kent Homecare LTD t/a The Garde...,Maidstone,ME15 6SX,Good
3576,1-9944023918,1-8805492948,Tendi Care,Aylesford,ME20 7FF,Good

In [41]:
print(
    homecare_kent[
        "currentRatings.overall.rating"
    ].value_counts(dropna=False)
)

currentRatings.overall.rating
Not rated               228
Good                    150
Requires improvement     28
Outstanding               9
Name: count, dtype: int64

# Final Kent Personal/Home Care Dataset

In [44]:
import json
import pandas as pd

with open("kent_care_homes.json", "r", encoding="utf-8") as file:
    kent_personal_care = json.load(file)

with open("medway_care_homes.json", "r", encoding="utf-8") as file:
    medway_personal_care = json.load(file)

print("Kent records:", len(kent_personal_care))
print("Medway records:", len(medway_personal_care))

Kent records: 3730
Medway records: 655

In [45]:
kent_clean = pd.json_normalize(kent_personal_care)

print("Rows:", len(kent_clean))
print("Columns:", len(kent_clean.columns))

Rows: 3730
Columns: 59

In [46]:
kent_clean.head(3)

,locationId,providerId,organisationType,type,name,brandId,brandName,onspdCcgCode,onspdCcgName,onspdIcbCode,...,odsCode,historicRatings,assessmentServiceGroup,assessment,dormancyEndDate,registeredManagerAbsentDate,alsoKnownAs,dormancyStartDate,unpublishedReports,providerInspectionAreas
0,1-1001764512,1-983441221,Location,Independent Healthcare Org,Optical Express - Bluewater Clinic,BD142,BRAND Optical Express,E38000237,NHS Kent and Medway CCG,E54000032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1-1002113960,1-942188853,Location,Social Care Org,Elmwood,NaN,NaN,E38000237,NHS Kent and Medway CCG,E54000032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1-10048396988,1-9931659218,Location,Primary Medical Services,Harbour Medical Practice,NaN,NaN,E38000237,NHS Kent and Medway CCG,E54000032,...,G82217,"[{'reportDate': '2017-08-07', 'reportLinkId': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
print(kent_clean.columns.tolist())

['locationId', 'providerId', 'organisationType', 'type', 'name', 'brandId', 'brandName', 'onspdCcgCode', 'onspdCcgName', 'onspdIcbCode', 'onspdIcbName', 'registrationStatus', 'registrationDate', 'deregistrationDate', 'dormancy', 'onspdLatitude', 'onspdLongitude', 'careHome', 'inspectionDirectorate', 'postalAddressLine1', 'postalAddressLine2', 'postalAddressTownCity', 'postalAddressCounty', 'region', 'postalCode', 'uprn', 'mainPhoneNumber', 'website', 'numberOfBeds', 'constituency', 'localAuthority', 'relationships', 'locationTypes', 'regulatedActivities', 'gacServiceTypes', 'specialisms', 'inspectionCategories', 'inspectionAreas', 'reports', 'lastInspection.date', 'lastReport.publicationDate', 'currentRatings.overall.rating', 'currentRatings.overall.reportDate', 'currentRatings.overall.reportLinkId', 'currentRatings.overall.keyQuestionRatings', 'currentRatings.reportDate', 'currentRatings.serviceRatings', 'odsCcgCode', 'odsCcgName', 'odsCode', 'historicRatings', 'assessmentServiceGroup', 'assessment', 'dormancyEndDate', 'registeredManagerAbsentDate', 'alsoKnownAs', 'dormancyStartDate', 'unpublishedReports', 'providerInspectionAreas']

In [48]:
print(kent_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3730 entries, 0 to 3729
Data columns (total 59 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   locationId                                 3730 non-null   object
 1   providerId                                 3730 non-null   object
 2   organisationType                           3730 non-null   object
 3   type                                       3730 non-null   object
 4   name                                       3730 non-null   object
 5   brandId                                    1203 non-null   object
 6   brandName                                  1203 non-null   object
 7   onspdCcgCode                               3724 non-null   object
 8   onspdCcgName                               3724 non-null   object
 9   onspdIcbCode                               3690 non-null   object
 10  onspdIcbName                               3690 non-null   object
 11  registrationStatus                         3730 non-null   object
 12  registrationDate                           3730 non-null   object
 13  deregistrationDate                         2054 non-null   object
 14  dormancy                                   3730 non-null   object
 15  onspdLatitude                              3729 non-null   float64
 16  onspdLongitude                             3729 non-null   float64
 17  careHome                                   3730 non-null   object
 18  inspectionDirectorate                      3730 non-null   object
 19  postalAddressLine1                         3730 non-null   object
 20  postalAddressLine2                         2007 non-null   object
 21  postalAddressTownCity                      3730 non-null   object
 22  postalAddressCounty                        2854 non-null   object
 23  region                                     3730 non-null   object
 24  postalCode                                 3730 non-null   object
 25  uprn                                       2365 non-null   object
 26  mainPhoneNumber                            3401 non-null   object
 27  website                                    2121 non-null   object
 28  numberOfBeds                               3567 non-null   float64
 29  constituency                               3730 non-null   object
 30  localAuthority                             3730 non-null   object
 31  relationships                              3730 non-null   object
 32  locationTypes                              3730 non-null   object
 33  regulatedActivities                        3730 non-null   object
 34  gacServiceTypes                            3730 non-null   object
 35  specialisms                                3730 non-null   object
 36  inspectionCategories                       3244 non-null   object
 37  inspectionAreas                            3730 non-null   object
 38  reports                                    2338 non-null   object
 39  lastInspection.date                        2352 non-null   object
 40  lastReport.publicationDate                 1817 non-null   object
 41  currentRatings.overall.rating              2252 non-null   object
 42  currentRatings.overall.reportDate          1592 non-null   object
 43  currentRatings.overall.reportLinkId        1592 non-null   object
 44  currentRatings.overall.keyQuestionRatings  2252 non-null   object
 45  currentRatings.reportDate                  1616 non-null   object
 46  currentRatings.serviceRatings              279 non-null    object
 47  odsCcgCode                                 306 non-null    object
 48  odsCcgName                                 305 non-null    object
 49  odsCode                                    2076 non-null   object
 50  historicRatings                            1176 non-null   object
 51  assessmentServiceGroup                     284 non-null    object
 52  assessment                                 284 non-null    object
 53  dormancyEndDate                            260 non-null    object
 54  registeredManagerAbsentDate                133 non-null    object
 55  alsoKnownAs                                158 non-null    object
 56  dormancyStartDate                          106 non-null    object
 57  unpublishedReports                         22 non-null     object
 58  providerInspectionAreas                    26 non-null     object
dtypes: float64(3), object(56)
memory usage: 1.7+ MB
None

In [49]:
print("Duplicate location IDs:",
      kent_clean["locationId"].duplicated().sum())

print("Duplicate provider IDs:",
      kent_clean["providerId"].duplicated().sum())

Duplicate location IDs: 0
Duplicate provider IDs: 1423

In [50]:
print(kent_clean["registrationStatus"].value_counts(dropna=False))

registrationStatus
Deregistered    2054
Registered      1676
Name: count, dtype: int64

In [51]:
print("Missing postcodes:",
      kent_clean["postalCode"].isna().sum())

print("Missing local authorities:",
      kent_clean["localAuthority"].isna().sum())

Missing postcodes: 0
Missing local authorities: 0

In [52]:
kent_registered = kent_clean[
    kent_clean["registrationStatus"].str.strip().str.lower() == "registered"
].copy()

print("Registered Kent locations:", len(kent_registered))

Registered Kent locations: 1676

In [53]:
print(
    kent_registered["currentRatings.overall.rating"]
    .value_counts(dropna=False)
)

currentRatings.overall.rating
NaN                        728
Good                       575
Inspected but not rated    180
Requires improvement        86
No published rating         72
Outstanding                 35
Name: count, dtype: int64

In [54]:
kent_registered["currentRatings.overall.rating"] = (
    kent_registered["currentRatings.overall.rating"]
    .fillna("Not rated")
)

print(
    kent_registered["currentRatings.overall.rating"]
    .value_counts()
)

currentRatings.overall.rating
Not rated                  728
Good                       575
Inspected but not rated    180
Requires improvement        86
No published rating         72
Outstanding                 35
Name: count, dtype: int64

In [55]:
kent_registered["postalCode"] = (
    kent_registered["postalCode"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

In [56]:
print("Missing postcodes:", kent_registered["postalCode"].isna().sum())

Missing postcodes: 0

In [57]:
town_counts = kent_registered["postalAddressTownCity"].value_counts()

print(town_counts)

postalAddressTownCity
Maidstone          166
Ashford            133
Dartford           121
Canterbury         120
Tunbridge Wells    105
                  ...
Southborough         1
Brenchley            1
Northfleet           1
Hythe, Kent          1
Isle of Sheppy       1
Name: count, Length: 64, dtype: int64

In [58]:
print("Unique towns:", kent_registered["postalAddressTownCity"].nunique())

Unique towns: 64

In [59]:
kent_registered["postalAddressTownCity"] = (
    kent_registered["postalAddressTownCity"]
    .astype("string")
    .str.strip()
)

kent_registered["postalAddressTownCity"] = kent_registered[
    "postalAddressTownCity"
].replace({
    "Westgate-on-sea": "Westgate On Sea"
})

In [60]:
print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Westgate", case=False, na=False)
    ]["postalAddressTownCity"].value_counts()
)

postalAddressTownCity
Westgate On Sea    8
Westgate-on-Sea    4
Name: count, dtype: Int64

In [61]:
print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Hythe", case=False, na=False)
    ]["postalAddressTownCity"].value_counts()
)

postalAddressTownCity
Hythe          26
Hythe, Kent     1
Name: count, dtype: Int64

In [62]:
print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Westgate", case=False, na=False)
    ]["postalAddressTownCity"].unique()
)

print(
    kent_registered[
        kent_registered["postalAddressTownCity"]
        .str.contains("Hythe", case=False, na=False)
    ]["postalAddressTownCity"].unique()
)

<StringArray>
['Westgate-on-Sea', 'Westgate On Sea']
Length: 2, dtype: string
<StringArray>
['Hythe', 'Hythe, Kent']
Length: 2, dtype: string

In [63]:
print("Missing registration dates:",
      kent_registered["registrationDate"].isna().sum())

print("Missing rating dates:",
      kent_registered["currentRatings.overall.reportDate"].isna().sum())

Missing registration dates: 0
Missing rating dates: 800

In [64]:
print(
    kent_registered["currentRatings.overall.rating"]
    .value_counts(dropna=False)
)

currentRatings.overall.rating
Not rated                  728
Good                       575
Inspected but not rated    180
Requires improvement        86
No published rating         72
Outstanding                 35
Name: count, dtype: int64

In [65]:
print("Duplicate location IDs:",
      kent_registered["locationId"].duplicated().sum())

Duplicate location IDs: 0

In [66]:
final_columns = [
    "locationId",
    "providerId",
    "name",
    "registrationStatus",
    "registrationDate",
    "postalAddressLine1",
    "postalAddressTownCity",
    "postalAddressCounty",
    "region",
    "postalCode",
    "mainPhoneNumber",
    "localAuthority",
    "numberOfBeds",
    "currentRatings.overall.rating",
    "currentRatings.overall.reportDate",
    "regulatedActivities",
    "gacServiceTypes"
]

kent_final = kent_registered[final_columns].copy()

print("Final rows:", len(kent_final))
print("Final columns:", len(kent_final.columns))

Final rows: 1676
Final columns: 17

In [67]:
kent_final.head()

,locationId,providerId,name,registrationStatus,registrationDate,postalAddressLine1,postalAddressTownCity,postalAddressCounty,region,postalCode,mainPhoneNumber,localAuthority,numberOfBeds,currentRatings.overall.rating,currentRatings.overall.reportDate,regulatedActivities,gacServiceTypes
2,1-10048396988,1-9931659218,Harbour Medical Practice,Registered,2021-03-24,Folkestone Health Centre,Folkestone,NaN,South East,CT20 1JY,01303220707,Kent,0.0,Good,2017-11-17,"[{'name': 'Maternity and midwifery services', ...","[{'name': 'Doctors/Gps', 'description': 'Docto..."
4,1-10064258273,1-9491037344,Kent Case Management Ltd,Registered,2020-12-30,"The Stables, Bradbourne House,",West Malling,NaN,South East,ME19 6DZ,07741497668,Kent,0.0,Good,2022-03-18,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."
5,1-10087632956,1-6192052130,Royalcare- Thanet,Registered,2020-12-23,Kent Innovation Centre,Broadstairs,Kent,South East,CT10 2QQ,01843838122,Kent,0.0,Requires improvement,2022-05-25,"[{'name': 'Personal care', 'code': 'RA1', 'con...","[{'name': 'Homecare agencies', 'description': ..."
7,1-1010200978,1-935571070,Ashlea House,Registered,2013-10-25,Bockhanger Lane,Ashford,Kent,South East,TN24 9BP,01233643635,Kent,4.0,Good,2019-07-12,[{'name': 'Accommodation for persons who requi...,"[{'name': 'Residential homes', 'description': ..."
8,1-1010201117,1-935571070,Birch House,Registered,2013-10-25,The Street,Ashford,Kent,South East,TN26 2AF,01233758527,Kent,5.0,Not rated,NaN,[{'name': 'Accommodation for persons who requi...,"[{'name': 'Residential homes', 'description': ..."

In [68]:
kent_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1676 entries, 2 to 3729
Data columns (total 17 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   locationId                         1676 non-null   object
 1   providerId                         1676 non-null   object
 2   name                               1676 non-null   object
 3   registrationStatus                 1676 non-null   object
 4   registrationDate                   1676 non-null   object
 5   postalAddressLine1                 1676 non-null   object
 6   postalAddressTownCity              1676 non-null   string
 7   postalAddressCounty                1029 non-null   object
 8   region                             1676 non-null   object
 9   postalCode                         1676 non-null   string
 10  mainPhoneNumber                    1529 non-null   object
 11  localAuthority                     1676 non-null   object
 12  numberOfBeds                       1630 non-null   float64
 13  currentRatings.overall.rating      1676 non-null   object
 14  currentRatings.overall.reportDate  876 non-null    object
 15  regulatedActivities                1676 non-null   object
 16  gacServiceTypes                    1676 non-null   object
dtypes: float64(1), object(14), string(2)
memory usage: 235.7+ KB

In [69]:
kent_final.to_csv(
    "kent_personal_homecare_clean.csv",
    index=False
)

print("CSV created successfully!")

CSV created successfully!